services:
  moog-agent:
    image: ghcr.io/cardano-foundation/moog/moog-agent:v0.4.0.0
    secrets:
      - agent-wallet
      - secrets
      - source: docker
        target: /run/secrets/docker/config.json
    environment:
      - MOOG_MPFS_HOST=http://10.1.21.21:3000
      - MOOG_WALLET_FILE=/run/secrets/agent-wallet
      - MOOG_TOKEN_ID=21c523c3b4565f1fc1ad7e54e82ca976f60997d8e7e9946826813fabf341069b
      - MOOG_SECRETS_FILE=/run/secrets/secrets
      - MOOG_WAIT=240
      - MOOG_ANTITHESIS_USER=cardano
      - DOCKER_CONFIG=/run/secrets/docker
    restart: always
    privileged: true
    command: "--poll-interval 60 --days 1 --trust-all-requesters"
    volumes:
      - tmp:/tmp
        # Mount CA certificates, curl seems not to find them when the pkgs.cacert is included in the image
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - /var/run/docker.sock:/var/run/docker.sock
secrets:
  agent-wallet:
    file: ./agent.json # Path to a file containing the wallet
  secrets:
    file: ./secrets.yaml # Path to a file containing the secrets
  docker:
    file: ./docker-config.json # Path to a file containing Docker config (for private registries)

volumes:
  tmp:
### Keys of the secrets.yaml file:
# agentEmail: # Email address where url links are received
# agentEmailPassword: # App password for the email account
# githubPAT: # GitHub Personal Access Token
# trustedRequesters:
#   - requester1
#   - requester2
# antithesisPassword: # Password for Antithesis registry and Docker image
